auth_timeout: 60.0
booking_timeout: 600.0
camera_index: 1
class_ids:
- 2
- 3
- 5
- 7
conf_threshold: 0.15
debug_locks: false
detect_every_n_frames: 2
distance_normalization: 1500.0
model_path: models/yolov8n-seg.pt
queue_zones:
- - - 40
    - 170
  - - 214
    - 173
  - - 226
    - 271
  - - 577
    - 265
  - - 580
    - 412
  - - 40
    - 419
rate_limit_attempts: 5
rate_limit_window: 60.0
slots:
- - - 63
    - 64
  - - 64
    - 128
  - - 192
    - 128
  - - 184
    - 64
- - - 254
    - 52
  - - 257
    - 115
  - - 399
    - 121
  - - 404
    - 45
- - - 255
    - 124
  - - 253
    - 221
  - - 468
    - 227
  - - 460
    - 125
- - - 532
    - 68
  - - 553
    - 183
  - - 611
    - 175
  - - 595
    - 64
strict_mode: false
